# Generated by Django 3.2.19 on 2023-06-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_rename_status_int_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.FileField(upload_to='assets/', verbose_name='изображение')),
                ('text', models.CharField(blank=True, max_length=120, null=True, verbose_name='Описание')),
            ],
        ),
    ]
